import os
import datetime

def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to Markdown file with proper formatting"""
    os.makedirs(directory, exist_ok=True)
    
    
    try:
        # Convert Markdown to HTML
        import markdown
        from xhtml2pdf import pisa
        
        # Replace problematic symbols with text equivalents for PDF compatibility
        text_to_convert = response_text.replace("₹", "Rs. ").replace("€", "EUR ").replace("£", "GBP ").replace("$", "USD ")
        
        # Add enhanced styling for the PDF
        html_content = f"""
        <html>
        <head>
            <style>
                @page {{
                    size: A4;
                    margin: 2cm;
                }}
                body {{ 
                    font-family: Helvetica, Arial, sans-serif; 
                    line-height: 1.6;
                    color: #333;
                }}
                h1 {{ 
                    color: #2C3E50; 
                    border-bottom: 2px solid #E74C3C; 
                    padding-bottom: 10px;
                    margin-top: 0;
                }}
                h2 {{ 
                    color: #2980B9; 
                    margin-top: 25px;
                    border-left: 5px solid #2980B9;
                    padding-left: 10px;
                }}
                h3 {{ 
                    color: #16A085; 
                    margin-top: 20px;
                }}
                p {{
                    margin-bottom: 15px;
                    text-align: justify;
                }}
                ul {{
                    margin-bottom: 15px;
                }}
                li {{
                    margin-bottom: 8px;
                }}
                .header-banner {{
                    background-color: #2C3E50;
                    color: white;
                    padding: 20px;
                    border-radius: 5px;
                    margin-bottom: 30px;
                    text-align: center;
                }}
                .header-banner h1 {{
                    color: white;
                    border: none;
                }}
                .metadata {{ 
                    margin-bottom: 20px; 
                    font-size: 0.9em;
                    color: #7F8C8D;
                    text-align: center;
                }}
                .footer {{ 
                    font-size: 9px; 
                    color: #95A5A6; 
                    margin-top: 50px; 
                    border-top: 1px solid #BDC3C7; 
                    padding-top: 15px;
                    text-align: center;
                }}
                strong {{
                    color: #E67E22;
                }}
            </style>
        </head>
        <body>
            <div class="header-banner">
                <h1>🌍 AI Travel Plan</h1>
            </div>
            
            <div class="metadata">
                <p><b>Generated on:</b> {datetime.datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
                <p><b>Created by:</b> AI Trip Planner Agent</p>
            </div>
            
            {markdown.markdown(text_to_convert)}
            
            <div class="footer">
                <p>This travel itinerary was generated by AI. Prices (Rs./USD/EUR), timings, and availability are subject to change. Please verify all details before booking.</p>
            </div>
        </body>
        </html>
        """

        # Generate timestamp-based filename
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.pdf"

        print(f"Generating PDF: {filename}")

        # Create the PDF
        with open(filename, "wb") as pdf_file:
            pisa_status = pisa.CreatePDF(html_content, dest=pdf_file)

        if pisa_status.err:
            print(f"Error generating PDF: {pisa_status.err}")
            return None
        
        print(f"PDF file saved as: {filename}")
        return filename
        
    except Exception as e:
        print(f"Error saving PDF file: {e}")
        return None